CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;


DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260713133447_InitialCreate') THEN
    CREATE TABLE access_logs (
        id integer GENERATED BY DEFAULT AS IDENTITY,
        user_id uuid NOT NULL,
        zone_id integer NOT NULL,
        log_date timestamp with time zone NOT NULL,
        log_type character varying(10) NOT NULL,
        CONSTRAINT "PK_access_logs" PRIMARY KEY (id)
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260713133447_InitialCreate') THEN
    CREATE TABLE "Project" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "Name" character varying(100) NOT NULL,
        "Description" character varying(500) NOT NULL,
        "StartDate" timestamp with time zone NOT NULL,
        "IsActive" boolean NOT NULL,
        CONSTRAINT "PK_Project" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260713133447_InitialCreate') THEN
    CREATE TABLE "Reports" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "Title" text NOT NULL,
        "CreatedAt" timestamp with time zone NOT NULL,
        CONSTRAINT "PK_Reports" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260713133447_InitialCreate') THEN
    CREATE TABLE roles (
        id uuid NOT NULL,
        name character varying(50) NOT NULL,
        normalized_name character varying(50) NOT NULL,
        description character varying(200),
        CONSTRAINT "PK_roles" PRIMARY KEY (id)
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260713133447_InitialCreate') THEN
    CREATE TABLE zones (
        id integer GENERATED BY DEFAULT AS IDENTITY,
        name character varying(100) NOT NULL,
        CONSTRAINT "PK_zones" PRIMARY KEY (id)
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260713133447_InitialCreate') THEN
    CREATE TABLE users (
        id uuid NOT NULL,
        name character varying(100) NOT NULL,
        email character varying(100) NOT NULL,
        role_id uuid NOT NULL,
        "PasswordHash" text NOT NULL,
        "PhoneNumber" text,
        "ProfileImageUrl" text,
        "IsEmailNotificationEnabled" boolean NOT NULL,
        "IsSmsNotificationEnabled" boolean NOT NULL,
        "ProjectId" integer,
        CONSTRAINT "PK_users" PRIMARY KEY (id),
        CONSTRAINT "FK_users_Project_ProjectId" FOREIGN KEY ("ProjectId") REFERENCES "Project" ("Id"),
        CONSTRAINT "FK_users_roles_role_id" FOREIGN KEY (role_id) REFERENCES roles (id) ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260713133447_InitialCreate') THEN
    CREATE TABLE permissions (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "UserId" uuid NOT NULL,
        "StartDate" timestamp with time zone NOT NULL,
        "EndDate" timestamp with time zone NOT NULL,
        "Reason" character varying(200) NOT NULL,
        "IsApproved" boolean NOT NULL,
        CONSTRAINT "PK_permissions" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_permissions_users_UserId" FOREIGN KEY ("UserId") REFERENCES users (id) ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260713133447_InitialCreate') THEN
    CREATE INDEX "IX_permissions_UserId" ON permissions ("UserId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260713133447_InitialCreate') THEN
    CREATE UNIQUE INDEX "IX_roles_name" ON roles (name);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260713133447_InitialCreate') THEN
    CREATE INDEX "IX_users_ProjectId" ON users ("ProjectId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260713133447_InitialCreate') THEN
    CREATE INDEX "IX_users_role_id" ON users (role_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260713133447_InitialCreate') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260713133447_InitialCreate', '8.0.11');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;


DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260714064520_AddMobileRefreshTokens') THEN
    CREATE TABLE refresh_tokens (
        id uuid NOT NULL,
        user_id uuid NOT NULL,
        token_hash character varying(128) NOT NULL,
        device_name character varying(150),
        created_at timestamp with time zone NOT NULL,
        expires_at timestamp with time zone NOT NULL,
        revoked_at timestamp with time zone,
        replaced_by_token_id uuid,
        CONSTRAINT "PK_refresh_tokens" PRIMARY KEY (id),
        CONSTRAINT "FK_refresh_tokens_users_user_id" FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260714064520_AddMobileRefreshTokens') THEN
    CREATE UNIQUE INDEX "IX_refresh_tokens_token_hash" ON refresh_tokens (token_hash);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260714064520_AddMobileRefreshTokens') THEN
    CREATE INDEX "IX_refresh_tokens_user_id" ON refresh_tokens (user_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260714064520_AddMobileRefreshTokens') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260714064520_AddMobileRefreshTokens', '8.0.11');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;


DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260714065156_AddMobileAccessEventIdentity') THEN
    ALTER TABLE access_logs ADD device_event_id character varying(100);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260714065156_AddMobileAccessEventIdentity') THEN
    ALTER TABLE access_logs ADD source character varying(30) NOT NULL DEFAULT 'Terminal';
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260714065156_AddMobileAccessEventIdentity') THEN
    CREATE UNIQUE INDEX "IX_access_logs_device_event_id" ON access_logs (device_event_id) WHERE device_event_id IS NOT NULL;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260714065156_AddMobileAccessEventIdentity') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260714065156_AddMobileAccessEventIdentity', '8.0.11');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;


DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260714065602_AddLeaveRequests') THEN
    CREATE TABLE leave_requests (
        id uuid NOT NULL,
        user_id uuid NOT NULL,
        leave_type integer NOT NULL,
        start_date date NOT NULL,
        end_date date NOT NULL,
        reason character varying(500),
        status integer NOT NULL,
        created_at timestamp with time zone NOT NULL,
        reviewed_at timestamp with time zone,
        reviewed_by_user_id uuid,
        review_note character varying(500),
        CONSTRAINT "PK_leave_requests" PRIMARY KEY (id),
        CONSTRAINT "FK_leave_requests_users_user_id" FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260714065602_AddLeaveRequests') THEN
    CREATE INDEX "IX_leave_requests_user_id_start_date_end_date" ON leave_requests (user_id, start_date, end_date);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260714065602_AddLeaveRequests') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260714065602_AddLeaveRequests', '8.0.11');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;


DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260714072908_AddNotifications') THEN
    CREATE TABLE notifications (
        id uuid NOT NULL,
        user_id uuid NOT NULL,
        type integer NOT NULL,
        title character varying(150) NOT NULL,
        message character varying(1000) NOT NULL,
        related_entity_id uuid,
        created_at timestamp with time zone NOT NULL,
        read_at timestamp with time zone,
        CONSTRAINT "PK_notifications" PRIMARY KEY (id),
        CONSTRAINT "FK_notifications_users_user_id" FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260714072908_AddNotifications') THEN
    CREATE INDEX "IX_notifications_user_id_read_at_created_at" ON notifications (user_id, read_at, created_at);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260714072908_AddNotifications') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260714072908_AddNotifications', '8.0.11');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;


DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260714074212_AddEmployeeAdministration') THEN
    ALTER TABLE users ADD department character varying(100);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260714074212_AddEmployeeAdministration') THEN
    ALTER TABLE users ADD employee_number character varying(40);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260714074212_AddEmployeeAdministration') THEN
    UPDATE users SET employee_number = 'LEGACY-' || UPPER(SUBSTRING(id::text, 1, 8)) WHERE employee_number IS NULL OR employee_number = '';
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260714074212_AddEmployeeAdministration') THEN
    ALTER TABLE users ALTER COLUMN employee_number SET NOT NULL;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260714074212_AddEmployeeAdministration') THEN
    ALTER TABLE users ADD hire_date date;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260714074212_AddEmployeeAdministration') THEN
    ALTER TABLE users ADD is_active boolean NOT NULL DEFAULT TRUE;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260714074212_AddEmployeeAdministration') THEN
    CREATE UNIQUE INDEX "IX_users_email" ON users (email);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260714074212_AddEmployeeAdministration') THEN
    CREATE UNIQUE INDEX "IX_users_employee_number" ON users (employee_number);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260714074212_AddEmployeeAdministration') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260714074212_AddEmployeeAdministration', '8.0.11');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;


DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260714074726_AddShiftScheduling') THEN
    CREATE TABLE shifts (
        id uuid NOT NULL,
        name character varying(100) NOT NULL,
        starts_at time without time zone NOT NULL,
        ends_at time without time zone NOT NULL,
        late_tolerance_minutes integer NOT NULL,
        early_leave_tolerance_minutes integer NOT NULL,
        break_minutes integer NOT NULL,
        is_active boolean NOT NULL,
        CONSTRAINT "PK_shifts" PRIMARY KEY (id)
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260714074726_AddShiftScheduling') THEN
    CREATE TABLE employee_shift_assignments (
        id uuid NOT NULL,
        employee_id uuid NOT NULL,
        shift_id uuid NOT NULL,
        valid_from date NOT NULL,
        valid_to date,
        CONSTRAINT "PK_employee_shift_assignments" PRIMARY KEY (id),
        CONSTRAINT "FK_employee_shift_assignments_shifts_shift_id" FOREIGN KEY (shift_id) REFERENCES shifts (id) ON DELETE RESTRICT,
        CONSTRAINT "FK_employee_shift_assignments_users_employee_id" FOREIGN KEY (employee_id) REFERENCES users (id) ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260714074726_AddShiftScheduling') THEN
    CREATE INDEX "IX_employee_shift_assignments_employee_id_valid_from_valid_to" ON employee_shift_assignments (employee_id, valid_from, valid_to);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260714074726_AddShiftScheduling') THEN
    CREATE INDEX "IX_employee_shift_assignments_shift_id" ON employee_shift_assignments (shift_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260714074726_AddShiftScheduling') THEN
    CREATE UNIQUE INDEX "IX_shifts_name" ON shifts (name);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260714074726_AddShiftScheduling') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260714074726_AddShiftScheduling', '8.0.11');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;


DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260714080646_AddAuditTrail') THEN
    CREATE TABLE audit_logs (
        id uuid NOT NULL,
        actor_user_id uuid,
        action character varying(80) NOT NULL,
        entity_type character varying(100) NOT NULL,
        entity_id character varying(100) NOT NULL,
        old_values_json jsonb,
        new_values_json jsonb,
        occurred_at timestamp with time zone NOT NULL,
        correlation_id character varying(100),
        CONSTRAINT "PK_audit_logs" PRIMARY KEY (id),
        CONSTRAINT "FK_audit_logs_users_actor_user_id" FOREIGN KEY (actor_user_id) REFERENCES users (id) ON DELETE SET NULL
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260714080646_AddAuditTrail') THEN
    CREATE INDEX "IX_audit_logs_actor_user_id" ON audit_logs (actor_user_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260714080646_AddAuditTrail') THEN
    CREATE INDEX "IX_audit_logs_entity_type_entity_id" ON audit_logs (entity_type, entity_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260714080646_AddAuditTrail') THEN
    CREATE INDEX "IX_audit_logs_occurred_at" ON audit_logs (occurred_at);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260714080646_AddAuditTrail') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260714080646_AddAuditTrail', '8.0.11');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;


DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260714081252_AddAttendanceCorrections') THEN
    CREATE TABLE attendance_correction_requests (
        id uuid NOT NULL,
        user_id uuid NOT NULL,
        work_date date NOT NULL,
        requested_entry time without time zone NOT NULL,
        requested_exit time without time zone NOT NULL,
        reason character varying(500) NOT NULL,
        status integer NOT NULL,
        created_at timestamp with time zone NOT NULL,
        reviewed_at timestamp with time zone,
        reviewed_by_user_id uuid,
        review_note character varying(500),
        CONSTRAINT "PK_attendance_correction_requests" PRIMARY KEY (id),
        CONSTRAINT "FK_attendance_correction_requests_users_user_id" FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260714081252_AddAttendanceCorrections') THEN
    CREATE INDEX "IX_attendance_correction_requests_user_id_work_date_status" ON attendance_correction_requests (user_id, work_date, status);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260714081252_AddAttendanceCorrections') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260714081252_AddAttendanceCorrections', '8.0.11');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;


DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260714082049_AddOrganizationStructure') THEN
    ALTER TABLE users ADD department_id uuid;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260714082049_AddOrganizationStructure') THEN
    ALTER TABLE users ADD workplace_id uuid;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260714082049_AddOrganizationStructure') THEN
    CREATE TABLE workplaces (
        id uuid NOT NULL,
        code character varying(30) NOT NULL,
        name character varying(120) NOT NULL,
        time_zone_id character varying(100) NOT NULL,
        address character varying(250),
        is_active boolean NOT NULL,
        CONSTRAINT "PK_workplaces" PRIMARY KEY (id)
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260714082049_AddOrganizationStructure') THEN
    CREATE TABLE departments (
        id uuid NOT NULL,
        workplace_id uuid NOT NULL,
        code character varying(30) NOT NULL,
        name character varying(120) NOT NULL,
        is_active boolean NOT NULL,
        CONSTRAINT "PK_departments" PRIMARY KEY (id),
        CONSTRAINT "FK_departments_workplaces_workplace_id" FOREIGN KEY (workplace_id) REFERENCES workplaces (id) ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260714082049_AddOrganizationStructure') THEN
    INSERT INTO workplaces (id, code, name, time_zone_id, address, is_active)
    VALUES ('00000000-0000-0000-0000-000000000001', 'MERKEZ', 'Merkez İşyeri', 'Europe/Istanbul', NULL, TRUE);

    INSERT INTO departments (id, workplace_id, code, name, is_active)
    SELECT md5('department:' || department)::uuid,
           '00000000-0000-0000-0000-000000000001',
           'LEG-' || UPPER(SUBSTRING(md5(department), 1, 8)),
           department,
           TRUE
    FROM (SELECT DISTINCT department FROM users WHERE department IS NOT NULL AND BTRIM(department) <> '') legacy;

    UPDATE users
    SET workplace_id = '00000000-0000-0000-0000-000000000001',
        department_id = CASE WHEN department IS NULL OR BTRIM(department) = ''
                             THEN NULL ELSE md5('department:' || department)::uuid END;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260714082049_AddOrganizationStructure') THEN
    CREATE INDEX "IX_users_department_id" ON users (department_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260714082049_AddOrganizationStructure') THEN
    CREATE INDEX "IX_users_workplace_id" ON users (workplace_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260714082049_AddOrganizationStructure') THEN
    CREATE UNIQUE INDEX "IX_departments_workplace_id_code" ON departments (workplace_id, code);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260714082049_AddOrganizationStructure') THEN
    CREATE UNIQUE INDEX "IX_workplaces_code" ON workplaces (code);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260714082049_AddOrganizationStructure') THEN
    ALTER TABLE users ADD CONSTRAINT "FK_users_departments_department_id" FOREIGN KEY (department_id) REFERENCES departments (id) ON DELETE SET NULL;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260714082049_AddOrganizationStructure') THEN
    ALTER TABLE users ADD CONSTRAINT "FK_users_workplaces_workplace_id" FOREIGN KEY (workplace_id) REFERENCES workplaces (id) ON DELETE SET NULL;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260714082049_AddOrganizationStructure') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260714082049_AddOrganizationStructure', '8.0.11');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;


DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260714082844_AddWorkCalendar') THEN
    CREATE TABLE work_calendar_days (
        id uuid NOT NULL,
        workplace_id uuid,
        date date NOT NULL,
        name character varying(150) NOT NULL,
        day_type integer NOT NULL,
        CONSTRAINT "PK_work_calendar_days" PRIMARY KEY (id),
        CONSTRAINT "FK_work_calendar_days_workplaces_workplace_id" FOREIGN KEY (workplace_id) REFERENCES workplaces (id) ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260714082844_AddWorkCalendar') THEN
    CREATE UNIQUE INDEX "IX_work_calendar_days_workplace_id_date" ON work_calendar_days (workplace_id, date);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260714082844_AddWorkCalendar') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260714082844_AddWorkCalendar', '8.0.11');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;


DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260714082925_EnforceGlobalCalendarUniqueness') THEN
    DROP INDEX "IX_work_calendar_days_workplace_id_date";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260714082925_EnforceGlobalCalendarUniqueness') THEN
    CREATE UNIQUE INDEX "IX_work_calendar_days_date" ON work_calendar_days (date) WHERE workplace_id IS NULL;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260714082925_EnforceGlobalCalendarUniqueness') THEN
    CREATE UNIQUE INDEX "IX_work_calendar_days_workplace_id_date" ON work_calendar_days (workplace_id, date) WHERE workplace_id IS NOT NULL;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260714082925_EnforceGlobalCalendarUniqueness') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260714082925_EnforceGlobalCalendarUniqueness', '8.0.11');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;


DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260714083407_AddAttendanceTerminals') THEN
    CREATE TABLE attendance_terminals (
        id uuid NOT NULL,
        workplace_id uuid NOT NULL,
        name character varying(100) NOT NULL,
        serial_number character varying(100) NOT NULL,
        api_key_hash character varying(64) NOT NULL,
        last_seen_at timestamp with time zone,
        firmware_version character varying(80),
        pending_event_count integer NOT NULL,
        last_error character varying(500),
        is_active boolean NOT NULL,
        created_at timestamp with time zone NOT NULL,
        CONSTRAINT "PK_attendance_terminals" PRIMARY KEY (id),
        CONSTRAINT "FK_attendance_terminals_workplaces_workplace_id" FOREIGN KEY (workplace_id) REFERENCES workplaces (id) ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260714083407_AddAttendanceTerminals') THEN
    CREATE UNIQUE INDEX "IX_attendance_terminals_serial_number" ON attendance_terminals (serial_number);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260714083407_AddAttendanceTerminals') THEN
    CREATE INDEX "IX_attendance_terminals_workplace_id" ON attendance_terminals (workplace_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260714083407_AddAttendanceTerminals') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260714083407_AddAttendanceTerminals', '8.0.11');
    END IF;
END $EF$;
COMMIT;

